-- Run with a Snowflake role that can create databases and tables.
CREATE DATABASE IF NOT EXISTS movieDB;
CREATE SCHEMA IF NOT EXISTS movieDB.PUBLIC;

CREATE TABLE IF NOT EXISTS movieDB.PUBLIC.VIDEO_POSTS (
  ID VARCHAR(36) NOT NULL PRIMARY KEY,
  SLUG VARCHAR(80) NOT NULL UNIQUE,
  TITLE VARCHAR(140) NOT NULL,
  CAPTION VARCHAR(600) NOT NULL DEFAULT '',
  CATEGORY VARCHAR(40) NOT NULL,
  LOCATION VARCHAR(120) NOT NULL DEFAULT '',
  RECORDED_AT DATE,
  DURATION_SECONDS NUMBER(38, 0) NOT NULL DEFAULT 0,
  VIDEO_FILE_NAME VARCHAR(255) NOT NULL,
  VIDEO_MIME_TYPE VARCHAR(100) NOT NULL,
  VIDEO_SIZE_BYTES NUMBER(38, 0) NOT NULL,
  VIDEO_STORAGE_MODE VARCHAR(40) NOT NULL DEFAULT 'snowflake_binary_chunks',
  POSTER_FILE_NAME VARCHAR(255),
  POSTER_MIME_TYPE VARCHAR(100),
  POSTER_DATA BINARY(1048576),
  IS_PUBLISHED BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PUBLISHED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS movieDB.PUBLIC.VIDEO_FILE_CHUNKS (
  VIDEO_ID VARCHAR(36) NOT NULL,
  CHUNK_INDEX NUMBER(38, 0) NOT NULL,
  CHUNK_DATA BINARY(4194304) NOT NULL,
  CREATED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (VIDEO_ID, CHUNK_INDEX)
);
